# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ed550fd4c41674ac94da5c0ffea8965e20477b38029585aac42e2204b11ef2b0b4912881b06d79c8fb6bed837f980e2b6d34e0e4bfed2fdf5926a4d916979ea7

test:
  secret_key_base: eb6c85f4397104f830c111445c28741ec44f3b3051c5647ef02baf5ebdf0c2a83550bb5c64cbafe64f913d1ae300d8359d05ebd1307537eccc8326accd684ef7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
